[General]
# acc version to use, must be supported by all servers listed
version = 1
# server identifies which server will be used
# 0 = switch between all, the others are numbered starting at 1
server = 1
# outgoing interface; comment out to autodetect
interface = "eno1"
# enable features (GfwEntropy, GfwSlowAscii, ...)
features = []
# enable verbose output; overrides CLI arg if present
# verbose = false
# daemonize (overrides CLI if present)
daemon = true

[[Server]]
# lowest and highest port in the dynamic range, inclusive
lowport = 53981
highport = 53981
# protocols: tcp, udp, http, https, etc
proto = "tcp"
# destination (IPv4 or IPv6)
ip = "10.4.0.1"
